name: markdown_editor
description: A set of utility widgets that convert Text to Markdown
version: 0.1.0
homepage: https://github.com/thunder-app/markdown-editor
repository: https://github.com/thunder-app/markdown-editor

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  expandable: ^5.0.1

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
